---
- name: Our first play
  hosts: planetexpress
  gather_facts: yes # runs by default

  tasks:

    - name: Install steam locomotive on ALL Ubuntu machines
      apt:
        name: sl
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "Ubuntu"

    - name: Install steam locomotive on all CentOS machines
      yum:
        name: sl
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "CentOS"
