---
- name: Copying content from controller to hosts
  hosts: planetexpress:!farnsworth
  gather_facts: yes # default is yes

  tasks:
    - name: Copy gather fact var data into hosts
      copy:
        src: ~/ipv4info.txt      # home directory on hosts
        remote_src: yes  
        dest: /tmp/moved.txt      # home directory on hosts
        backup: yes   # make backup of original
        force: yes    # file always copied when content is diff

