---
- name: Tuesday Challenge
  hosts: planetexpress
  connection: ssh
  gather_facts: yes

  tasks:
   
   - name: create a directory
     file: 
         path: ~/challenge
         state: directory
   
   - name: creating a file
     copy:
        dest: ~/challenge/challengefile.txt
        content: "Success!"
       
